@username=vidar.kongsli@felleskjopet.no
@pat=r5fwdcfmjnbwi6usc5ct5g46slrz2pzgd2vkhjobnsi2leqlxjeq
@organization=felleskjopet
@project=felleskjopet.no
@repositoryId=identity

# 

GET https://dev.azure.com/{{organization}}/{{project}}/_apis/build/builds
    ?api-version=5.1
    &statusFilter=completed
    &resultFilter=succeeded
    &queryOrder=finishTimeDescending
    &minTime=2020-06-22T00:00:00Z
Authorization: Basic {{username}}:{{pat}}

###

GET https://dev.azure.com/felleskjopet/e9895542-cc2b-441c-8706-cd727f539091/_apis/build/builds/45668/Timeline
Authorization: Basic {{username}}:{{pat}}


###

# GET Commits on master
GET https://dev.azure.com/{{organization}}/{{project}}/_apis/git/repositories/{{repositoryId}}/commits
    ?api-version=5.1
    &searchCriteria.$top=1
    &searchCriteria.itemVersion.version=master
    &searchCriteria.itemVersion.versionType=branch
    &searchCriteria.includeWorkItems=true
Authorization: Basic {{username}}:{{pat}}

###

# GET tags
GET https://dev.azure.com/{{organization}}/{{project}}/_apis/git/repositories/{{repositoryId}}/refs
    ?api-version=5.1
    &filter=tags/v
Authorization: Basic {{username}}:{{pat}}


###

# Get commits between tag and branch/commit/tag
POST https://dev.azure.com/{{organization}}/{{project}}/_apis/git/repositories/{{repositoryId}}/commitsbatch
    ?api-version=5.1
Authorization: Basic {{username}}:{{pat}}
Content-Type: application/json

{
  "itemVersion": {
    "versionType": "tag",
    "version": "v1.13.1"
  },
  "compareVersion": {
    "versionType": "branch",
    "version": "master"
  },
  "includeWorkItems":true
}

###

@wi=46122
# Get a work item
GET https://dev.azure.com/{{organization}}/{{project}}/_apis/wit/workItems/{{wi}}
Authorization: Basic {{username}}:{{pat}}

### 

#Get work items batch
POST https://dev.azure.com/{{organization}}/{{project}}/_apis/wit/workitemsbatch?api-version=6.0
Authorization: Basic {{username}}:{{pat}}
Content-Type: application/json

{
  "ids": [
    46122
  ],
  "fields": [
    "System.Id",
    "System.Title",
    "System.WorkItemType",
    "Microsoft.VSTS.Scheduling.RemainingWork"
  ]
}
