name: 1.0$(Rev:.r)

# trigger:
#   branches:
#     include:
#       - master

pool:
  vmImage: ubuntu-latest

variables:
  namePrefix: spdy-ng
  dockerRegistryServiceConnection: $(namePrefix)-acr
  registryName: 'spdyng.azurecr.io'
  repository: 'demos/$(namePrefix)'
  imageNameNoTag: $(registryName)/$(repository)
  imageName: $(imageNameNoTag):$(build.buildNumber)
  imageNameLatest: $(imageNameNoTag):latest

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: $(dockerRegistryServiceConnection)

- publish: $(DOCKER_CONFIG)
  artifact: Docka

- pwsh: |
    $x = Get-Content $env:DOCKER_CONFIG/config.json | ConvertFrom-Json
    Write-host
  displayName: Set version info
  inputs:
    targetType: inline
    script: ls -la $DOCKER_CONFIG/trust && cat $DOCKER_CONFIG/config.json

- script: docker build -f Dockerfile_agent -t $(imageName) -t $(imageNameLatest) .
  displayName: 'docker build'
  workingDirectory: agents
  
- task: Docker@2
  displayName: Push an image to container registry
  inputs:
    command: push
    repository: $(repository)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(build.buildNumber)
      latest
