
variables:
  registryName: 'spdyng.azurecr.io'
  namePrefix: spdy-ng
  dockerRegistryServiceConnection: $(namePrefix)-acr
  repository: 'demos/$(namePrefix)'
  imageNameNoTag: $(registryName)/$(repository)
  imageName: $(imageNameNoTag):$(build.buildNumber)
  imageNameLatest: $(imageNameNoTag):latest
  checkImageUri: https://$(registryName)/v2/demos/$(namePrefix)/tags/list

trigger:
  branches:
    include:
      - master

jobs:
  - job: prepareDockerImage
    displayName: Detect Docker image
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
    - pwsh: |
        $ErrorActionPreference='stop'
        $hash = ('agents/Dockerfile_agent','agents/testapp/package-lock.json' | ForEach-Object { Get-Content $_ } | Out-String | sha1sum -).Substring(0, 40) 
        echo "##vso[task.setvariable variable=hash;isOutput=true]$hash"
        Write-host "Image hash is $hash"
        $serviceConnection = Get-Content '$(DOCKER_CONFIG)/config.json' | ConvertFrom-Json
        $requestHeaders = @{'Authorization'='Basic ' + $serviceConnection.auths.'$(registryName)'.auth}
        $response = Invoke-WebRequest -uri '$(checkImageUri)' -Headers $requestHeaders
        if ($response.StatusCode -ne 200) {
          Write-Error "ACR response: " + $response.StatusCode + " for $(checkImageUri)"
        }
        $tags = $response `
          | Select-Object -ExpandProperty Content `
          | ConvertFrom-Json `
          | Select-Object -ExpandProperty tags
        $imageExists = $tags -Contains $hash
        Write-host "Image exists: $imageExists"
        echo "##vso[task.setvariable variable=imageExists;isOutput=true]$imageExists"
      name: imageDetect
      displayName: Calculate image hash and check if image exists in ACR

    - task: Docker@2
      displayName: Login to ACR
      condition: and(succeeded(),eq(variables['imageDetect.imageExists'],'False'))
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
      
    - script: docker build -f Dockerfile_agent -t $(imageName) -t $(imageNameLatest) .
      displayName: Build docker image
      condition: and(succeeded(),eq(variables['imageDetect.imageExists'],'False'))
      workingDirectory: agents
        
    - task: Docker@2
      displayName: Push image to container registry
      condition: and(succeeded(),eq(variables['imageDetect.imageExists'],'False'))
      inputs:
        command: push
        repository: $(repository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $[ variables['imageDetect.hash'] ]
          $(build.buildNumber)
          latest

  - job: buildApp
    displayName: Build application job
    pool:
      vmImge: 'ubuntu-16.04'
    dependsOn: prepareDockerImage
    condition: succeeded()
    variables:
      image: $[join(variables.repository,':',dependencies.prepareDockerImage.outputs['imageDetect.hash'])]
    container:
      image: $[ variables.image ]
      endpoint: spdy-ng-acr
    steps:
      - script: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          ln -s /src/node_modules node_modules
          npm run test_ci
          npm run build_ci
        workingDirectory: agents/testapp
        displayName: Run unit tests and build app for production
