name: 1.0$(Rev:.r)

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

variables:
  namePrefix: spdy-ng
  dockerRegistryServiceConnection: $(namePrefix)-acr
  registryName: '$(namePrefix).azurecr.io'
  repository: 'demos/$(namePrefix)'
  imageNameNoTag: $(registryName)/$(repository)
  imageName: $(imageNameNoTag):$(build.buildNumber)
  imageNameLatest: $(imageNameNoTag):latest

steps:
- task: Bash@3
  displayName: Set version info
  inputs:
    targetType: inline
    script: 'echo -ne "$(build.buildNumber)"'

- script: docker build -f agent/Dockerfile_agent -t $(imageName) -t $(imageNameLatest) .
  displayName: 'docker build'
  workingDirectory: agents

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: $(dockerRegistryServiceConnection)
  
- task: Docker@2
  displayName: Push an image to container registry
  inputs:
    command: push
    repository: $(repository)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(build.buildNumber)
      latest
