
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: npm@1
  displayName: Npm install
  inputs:
    command: custom
    customCommand: ci
    workingDir: agents/testapp

- task: npm@1
  displayName: Run tests
  inputs:
    command: custom
    customCommand: test_ci 
    workingDir: agents/testapp

- task: npm@1
  displayName: Build app
  inputs:
    command: custom
    customCommand: build_ci 
    workingDir: agents/testapp

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: agents/testapp/dist
    artifactName: app
