
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: 'demos/spdy-ng:latest'
  endpoint: spdy-ng-acr

steps:
- script: |
    set
    node --version
    npm --version
    npm ci
    npm run test_ci
    npm run build_ci
  workingDirectory: agents/testapp
#ln -s /src/node_modules node_modules
  