
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: 'demos/spdy-ng:latest'
  endpoint: spdy-ng-acr

steps:
- script: |
    set
    mv /src/node_modules .
    ng test --browser ChromeHeadlessNoSandbox
    npm run build --production
