
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: 'demos/spdy-ng:latest'
  endpoint: spdy-ng-acr

steps:
- script: |
    set
    node --version
    npm --version
    ln -s /src/node_modules node_modules
    npm run test --browser ChromeHeadlessNoSandbox
    npm run build --production
  workingDirectory: agents/testapp
